# Generated by Django 3.1.5 on 2021-01-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(default='')),
                ('name', models.CharField(default='', max_length=10)),
                ('marks_maths', models.IntegerField(default='')),
                ('marks_physics', models.IntegerField(default='')),
                ('marks_chem', models.IntegerField(default='')),
                ('marks_total', models.IntegerField(default='')),
                ('percent', models.IntegerField(default='')),
            ],
        ),
    ]
